### PR TITLE
feat: UI Modifications.

### PR DESCRIPTION
**Pull request by AbdallaEmadEldinAbdalla**
## Checklist:

- [ ] I have updated the app changelog
- [ ] I have made corresponding changes to the documentation
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings on the linter

### CODE REVIEW

**Comment by alex-greenbull** [comment]
trade screen 
make layout single colum on smaller screen 
trade type buttons should be full width
Screenshot_Trade  ARYA Crypto_002220

**Comment by alex-greenbull** [comment]
dashboard

Can we have a switch button to show / hide pie chart?

Screenshot_My Portfolio  ARYA Crypto_002222

**Comment by alex-greenbull** [comment]
settings
hide those 2 sections if no link is provided
Screenshot_Settings  ARYA Crypto_002224

**Comment by alex-greenbull** [comment]
Screenshot_Settings  ARYA Crypto_002226
i think theres a layourt issue here

**Review by almujtabamohammed — APPROVED** [review]

**Pull request merged**
